// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokMultilink, StoryblokRichtext, StoryblokAsset } from '../storyblok.d.ts';
export interface SbButton {
  label: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  submit?: boolean;
  type: "primary" | "secondary" | "tertiary";
  component: "button";
  _uid: string;
  [k: string]: any;
}

export interface SbConfig {
  header_menu?: SbMenuLink[];
  footer_menu?: SbMenuLink[];
  component: "config";
  _uid: string;
  [k: string]: any;
}

export interface SbFeature {
  name: string;
  image: StoryblokAsset;
  link_label: string;
  link: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "feature";
  _uid: string;
  [k: string]: any;
}

export interface SbGrid {
  columns?: (SbButton | SbConfig | SbFeature | SbGrid | SbHero | SbMenuLink | SbPage | SbTeaser)[];
  component: "grid";
  _uid: string;
  [k: string]: any;
}

export interface SbHero {
  announcement_text?: string;
  announcement_link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  title: string;
  subtitle?: StoryblokRichtext;
  cta?: SbButton[];
  image?: StoryblokAsset;
  component: "hero";
  _uid: string;
  [k: string]: any;
}

export interface SbMenuLink {
  name?: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "menu_link";
  _uid: string;
  [k: string]: any;
}

export interface SbPage {
  seo?: any;
  body?: (SbButton | SbConfig | SbFeature | SbGrid | SbHero | SbMenuLink | SbPage | SbTeaser)[];
  component: "page";
  _uid: string;
  [k: string]: any;
}

export interface SbTeaser {
  headline?: string;
  cta?: SbButton[];
  description?: StoryblokRichtext;
  component: "teaser";
  _uid: string;
  [k: string]: any;
}

export type ContentType = SbConfig | SbPage;
